stages:
# 單一專案多個資料庫部屬(1/3)
- name: Deploy app-db-test
  steps:
    - applyAppConfig:
        catalogTemplate: cattle-global-data:iii-dev-charts3-db
        version: 0.1.0
        name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
        targetNamespace: p-v2nzs-pipeline
        answers:
          # 這裡是為了50與140環境測試
          git.host: "10.50.1.53"
          # 這裡是為了告訴要處理的git來源為何
          git.repoName: ${CICD_GIT_REPO_NAME}
          git.branch: ${CICD_GIT_BRANCH}
          # 使用者參數(部屬) 預設都是true
          db.enabled: true
          db.gui: true
          # 使用者參數(資料庫)
          db.type: mysql
          db.tag: 5.7
          # 使用者參數(資料庫)帳號密碼
          db.username: bear44
          db.password: bearisbear44
          # 使用者參數(資料庫)資料庫名稱
          db.name: health44
